-- ============================================================================
--  VMetrix Query Manager — seed data
--  (1) model seed  = the sample dataset from Section 3 of the challenge
--  (2) metadata seed = the META_* rows describing the model to the engine
--
--  Reading notes on the sample dataset (see docs/ai-log.md):
--   - equity(3)/fund(6): source shows no maturity -> MATURITY_DATE = NULL, COUPON_RATE = 0.
--   - CREATED_AT (NOT NULL, absent from the sample) is seeded deterministically as
--     TXN_DATE at 09:30:00 so the 'timestamp' data type has real values to exercise.
--   - NOMINAL_VALUE (absent from the sample) is left NULL.
-- ============================================================================

-- ---------------------------------------------------------------------------
--  1. MODEL SEED  (order: PARTY -> INSTRUMENT -> TRANSACTION for FK integrity)
-- ---------------------------------------------------------------------------

-- PARTY (10 records)
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (1,  'Banco de Chile',           'COUNTERPARTY', '97-004-000-5', 'CL', 'Banking',    'AA',  1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (2,  'Tesoreria General',        'ISSUER',       '60-805-000-0', 'CL', 'Government', 'AAA', 1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (3,  'Falabella S.A.',           'ISSUER',       '90-743-000-0', 'CL', 'Retail',     'A+',  1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (4,  'BTG Pactual',              'BROKER',       '30-306-294-3', 'BR', 'Banking',    'AA-', 1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (5,  'Goldman Sachs',            'COUNTERPARTY', '13-5108880',   'US', 'Banking',    'A+',  1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (6,  'Ecopetrol S.A.',           'ISSUER',       '899999068-1',  'CO', 'Energy',     'BBB', 1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (7,  'Corp. Nacional del Cobre', 'ISSUER',       '61-704-000-K', 'CL', 'Mining',     'A+',  1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (8,  'AFP Habitat',              'COUNTERPARTY', '98-000-100-8', 'CL', 'Pension',    'AA+', 1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (9,  'Itau Unibanco',            'BROKER',       '60-872-504-4', 'BR', 'Banking',    'AA-', 1);
INSERT INTO PARTY (PARTY_ID, PARTY_NAME, PARTY_TYPE, TAX_ID, COUNTRY, SECTOR, RATING, IS_ACTIVE) VALUES
    (10, 'Inactive Corp',            'COUNTERPARTY', '99-999-999-9', 'CL', 'Other',      'NR',  0);

-- INSTRUMENT (8 records)
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (1, 'BTP-0230',  'Bono Tesoreria 2030',  'BOND',    'FIXED_INCOME', 2, 'CLP', DATE '2030-07-01', 3.50, NULL, 1);
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (2, 'BCU-0528',  'BCU 5Y UF 2028',       'BOND',    'FIXED_INCOME', 2, 'CLF', DATE '2028-05-15', 2.80, NULL, 1);
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (3, 'FALABELLA', 'Falabella Equity',     'EQUITY',  'EQUITY',       3, 'CLP', NULL,              0,    NULL, 1);
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (4, 'ECO-2031',  'Ecopetrol Bond 2031',  'BOND',    'FIXED_INCOME', 6, 'USD', DATE '2031-11-20', 5.25, NULL, 1);
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (5, 'CODELCO29', 'Codelco Bond 2029',    'BOND',    'FIXED_INCOME', 7, 'USD', DATE '2029-03-15', 4.10, NULL, 1);
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (6, 'FONDO-A',   'Fondo Mutuo Alpha',    'FUND',    'ALTERNATIVES', 1, 'CLP', NULL,              0,    NULL, 1);
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (7, 'USD-DEP',   'USD Time Deposit 90d', 'DEPOSIT', 'FIXED_INCOME', 5, 'USD', DATE '2026-07-15', 5.40, NULL, 1);
INSERT INTO INSTRUMENT (INSTRUMENT_ID, TICKER, INSTRUMENT_NAME, INSTRUMENT_TYPE, ASSET_CLASS, ISSUER_ID, CURRENCY, MATURITY_DATE, COUPON_RATE, NOMINAL_VALUE, IS_ACTIVE) VALUES
    (8, 'OLD-BOND',  'Expired Bond 2020',    'BOND',    'FIXED_INCOME', 3, 'CLP', DATE '2020-01-01', 6.00, NULL, 0);

-- TRANSACTION (15 records). SETTLEMENT_DATE is NULL for unsettled rows (9, 10, 14, 15).
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (1,  DATE '2026-01-10', 'BUY',      50000,   98.50,   4925000,  'CLP', 'SETTLED',   DATE '2026-01-12', 100, 1, 1, TIMESTAMP '2026-01-10 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (2,  DATE '2026-01-15', 'BUY',      10000,   102.30,  1023000,  'CLF', 'SETTLED',   DATE '2026-01-17', 100, 2, 1, TIMESTAMP '2026-01-15 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (3,  DATE '2026-01-20', 'BUY',      5000,    2350,    11750000, 'CLP', 'SETTLED',   DATE '2026-01-22', 200, 3, 4, TIMESTAMP '2026-01-20 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (4,  DATE '2026-02-01', 'BUY',      2000000, 99.75,   1995000,  'USD', 'SETTLED',   DATE '2026-02-03', 100, 4, 5, TIMESTAMP '2026-02-01 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (5,  DATE '2026-02-10', 'BUY',      3000000, 100.10,  3003000,  'USD', 'SETTLED',   DATE '2026-02-12', 100, 5, 5, TIMESTAMP '2026-02-10 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (6,  DATE '2026-02-15', 'SELL',     25000,   99.20,   2480000,  'CLP', 'SETTLED',   DATE '2026-02-17', 100, 1, 8, TIMESTAMP '2026-02-15 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (7,  DATE '2026-03-01', 'BUY',      100000,  10.50,   1050000,  'CLP', 'APPROVED',  DATE '2026-03-03', 200, 6, 1, TIMESTAMP '2026-03-01 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (8,  DATE '2026-03-05', 'COUPON',   50000,   3.50,    1750,     'CLP', 'SETTLED',   DATE '2026-03-05', 100, 1, 2, TIMESTAMP '2026-03-05 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (9,  DATE '2026-03-10', 'BUY',      5000000, 100.00,  5000000,  'USD', 'PENDING',   NULL,              300, 7, 5, TIMESTAMP '2026-03-10 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (10, DATE '2026-03-15', 'SELL',     2500,    2480,    6200000,  'CLP', 'PENDING',   NULL,              200, 3, 9, TIMESTAMP '2026-03-15 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (11, DATE '2026-03-20', 'DIVIDEND', 5000,    120,     600000,   'CLP', 'SETTLED',   DATE '2026-03-22', 200, 3, 3, TIMESTAMP '2026-03-20 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (12, DATE '2026-04-01', 'BUY',      1000000, 98.90,   989000,   'USD', 'APPROVED',  DATE '2026-04-03', 300, 4, 4, TIMESTAMP '2026-04-01 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (13, DATE '2026-04-05', 'MATURITY', 100000,  100.00,  10000000, 'CLP', 'SETTLED',   DATE '2026-04-05', 100, 8, 3, TIMESTAMP '2026-04-05 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (14, DATE '2026-04-10', 'SELL',     1500000, 100.50,  1507500,  'USD', 'CANCELLED', NULL,              100, 5, 5, TIMESTAMP '2026-04-10 09:30:00');
INSERT INTO TRANSACTION (TXN_ID, TXN_DATE, TXN_TYPE, QUANTITY, PRICE, AMOUNT, CURRENCY, STATUS, SETTLEMENT_DATE, PORTFOLIO_ID, INSTRUMENT_ID, COUNTERPARTY_ID, CREATED_AT) VALUES
    (15, DATE '2026-04-12', 'BUY',      20000,   101.20,  2024000,  'CLF', 'PENDING',   NULL,              100, 2, 8, TIMESTAMP '2026-04-12 09:30:00');

-- ---------------------------------------------------------------------------
--  2. METADATA SEED  (describes the model above to the engine)
-- ---------------------------------------------------------------------------

-- Entities
INSERT INTO META_ENTITY (ENTITY, PHYSICAL_TABLE, DEFAULT_ALIAS, DESCRIPTION) VALUES
    ('transaction', 'TRANSACTION', 't', 'Trade / cash-flow events');
INSERT INTO META_ENTITY (ENTITY, PHYSICAL_TABLE, DEFAULT_ALIAS, DESCRIPTION) VALUES
    ('instrument',  'INSTRUMENT',  'i', 'Financial instruments');
INSERT INTO META_ENTITY (ENTITY, PHYSICAL_TABLE, DEFAULT_ALIAS, DESCRIPTION) VALUES
    ('party',       'PARTY',       'p', 'Legal entities (counterparties, issuers, brokers, custodians)');

-- Fields: transaction
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'txnId',          'TXN_ID',          'number',    1, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'txnDate',        'TXN_DATE',        'date',      0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'txnType',        'TXN_TYPE',        'string',    0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'quantity',       'QUANTITY',        'number',    0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'price',          'PRICE',           'number',    0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'amount',         'AMOUNT',          'number',    0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'currency',       'CURRENCY',        'string',    0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'status',         'STATUS',          'string',    0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'settlementDate', 'SETTLEMENT_DATE', 'date',      0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'portfolioId',    'PORTFOLIO_ID',    'number',    0, NULL,         NULL,       1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'instrumentId',   'INSTRUMENT_ID',   'number',    0, 'instrument', 'instrumentId', 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'counterpartyId', 'COUNTERPARTY_ID', 'number',    0, 'party',      'partyId',      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('transaction', 'createdAt',      'CREATED_AT',      'timestamp', 0, NULL,         NULL,       1, 1);

-- Fields: party
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'partyId',   'PARTY_ID',   'number', 1, NULL, NULL, 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'partyName', 'PARTY_NAME', 'string', 0, NULL, NULL, 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'partyType', 'PARTY_TYPE', 'string', 0, NULL, NULL, 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'taxId',     'TAX_ID',     'string', 0, NULL, NULL, 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'country',   'COUNTRY',    'string', 0, NULL, NULL, 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'sector',    'SECTOR',     'string', 0, NULL, NULL, 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'rating',    'RATING',     'string', 0, NULL, NULL, 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('party', 'isActive',  'IS_ACTIVE',  'number', 0, NULL, NULL, 1, 1);

-- Fields: instrument
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'instrumentId',   'INSTRUMENT_ID',   'number', 1, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'ticker',         'TICKER',          'string', 0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'instrumentName', 'INSTRUMENT_NAME', 'string', 0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'instrumentType', 'INSTRUMENT_TYPE', 'string', 0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'assetClass',     'ASSET_CLASS',     'string', 0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'issuerId',       'ISSUER_ID',       'number', 0, 'party', 'partyId', 1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'currency',       'CURRENCY',        'string', 0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'maturityDate',   'MATURITY_DATE',   'date',   0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'couponRate',     'COUPON_RATE',     'number', 0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'nominalValue',   'NOMINAL_VALUE',   'number', 0, NULL,    NULL,      1, 1);
INSERT INTO META_FIELD (ENTITY, NAME, PHYSICAL_NAME, DATA_TYPE, PK, FK_ENTITY, FK_FIELD, FILTERABLE, SELECTABLE) VALUES
    ('instrument', 'isActive',       'IS_ACTIVE',       'number', 0, NULL,    NULL,      1, 1);

-- Relations (JOIN edges). Source/target fields are logical names, resolved to columns via META_FIELD.
INSERT INTO META_RELATION (ALIAS, SOURCE_ENTITY, SOURCE_FIELD, TARGET_ENTITY, TARGET_FIELD, JOIN_TYPE) VALUES
    ('instrument',   'transaction', 'instrumentId',   'instrument', 'instrumentId', 'LEFT');
INSERT INTO META_RELATION (ALIAS, SOURCE_ENTITY, SOURCE_FIELD, TARGET_ENTITY, TARGET_FIELD, JOIN_TYPE) VALUES
    ('counterparty', 'transaction', 'counterpartyId', 'party',      'partyId',      'LEFT');
INSERT INTO META_RELATION (ALIAS, SOURCE_ENTITY, SOURCE_FIELD, TARGET_ENTITY, TARGET_FIELD, JOIN_TYPE) VALUES
    ('issuer',       'instrument',  'issuerId',       'party',      'partyId',      'LEFT');

-- Comparator x data-type matrix (spec 5.3).
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('string', 'equals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('string', 'notEquals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('string', 'like');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('string', 'in');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('string', 'notIn');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('string', 'isNull');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('string', 'isNotNull');

INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'equals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'notEquals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'greaterThan');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'lessThan');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'greaterOrEqual');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'lessOrEqual');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'between');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'in');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'isNull');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('number', 'isNotNull');

INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'equals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'notEquals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'greaterThan');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'lessThan');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'greaterOrEqual');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'lessOrEqual');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'between');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'isNull');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('date', 'isNotNull');

INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'equals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'notEquals');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'greaterThan');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'lessThan');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'greaterOrEqual');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'lessOrEqual');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'isNull');
INSERT INTO META_COMPARATOR (DATA_TYPE, COMPARATOR) VALUES ('timestamp', 'isNotNull');
